### ISSUE TITLE
pip install -r ./src/requirements.txt failed

### ISSUE THREAD

**Issue by zuowanbushiwo** [eagomez2/upf-smc-speech-enhancement-thesis#2]
Hi  Esteban
     Thanks，This is a very good project and I plan to study it carefully to start my Deep Noise Suppression new work。
     But I failed to install the dependencies in the first step. I did the following steps:

  - virtualenv  -p /usr/bin/python3.6  buildenv
  - source ./buildenv/bin/activate
 - pip install -r ./src/requirements.txt
 
Error：

>  ERROR: Could not install packages due to an OSError: [Errno 2] does not have that file or directory: '/tmp/build/80754af9/mkl_random_1618853849286/work'

 in  `requirements.txt `     have   `mkl-random @ file:///tmp/build/80754af9/mkl_random_1618853849286/work `   `numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1618497241363/work`   those  packages do not specify a specific version .

how to fixed ?
Looking forward to your reply 

All the best

**Comment by zuowanbushiwo** [comment]
@eagomez2 
What version of python are you using? Is Python 3.6.9 OK?

**Comment by zuowanbushiwo** [comment]
@eagomez2 
Which version of numpy? why  numpy-1.22.4 not?   my Python version is 3.8.0 , thanks!
The conflict is caused by:
    The user requested numpy
    ear 2.0.0 depends on numpy~=1.14
    h5py 2.10.0 depends on numpy>=1.7
    keras-preprocessing 1.1.2 depends on numpy>=1.9.1
    librosa 0.8.0 depends on numpy>=1.15.0
    matplotlib 3.4.1 depends on numpy>=1.16
    mkl-fft 1.3.0 depends on numpy>=1.16
    numba 0.53.1 depends on numpy>=1.15
    onnxruntime 1.7.0 depends on numpy>=1.16.6
    opt-einsum 3.3.0 depends on numpy>=1.7
    pandas 1.2.4 depends on numpy>=1.16.5
    pytorch-lightning 1.2.10 depends on numpy>=1.16.6
    resampy 0.2.2 depends on numpy>=1.10
    scikit-learn 0.24.2 depends on numpy>=1.13.3
    scipy 1.6.3 depends on numpy<1.23.0 and >=1.16.5
    tensorboard 2.4.1 depends on numpy>=1.12.0
    tensorflow 2.4.1 depends on numpy~=1.19.2
    torch 1.8.1 depends on numpy
    torchvision 0.9.1 depends on numpy
    mkl-random 1.2.2 depends on numpy<1.23.0 and >=1.22.3

**Comment by eagomez2** [comment]
Hi @zuowanbushiwo,

I usually use `conda` to set up my environments. I don't know if `virtualenv` has perhaps something particularly different that is causing you these issues. `python 3.6.9` or anything above that should be okay. I started the project in `3.6.x` in fact.

I didn't install the `numpy` version manually. It was installed as a dependency of another module, that's why it may not use the latest version. As of now, I have `numpy 1.19.2` in my main environment.

I will try to recreate the install of this repo from scratch and update this issue accordingly.

**Comment by eagomez2** [comment]
Hi @zuowanbushiwo,

This `requirements.txt` seems to work with no issues in my machine running `python 3.8.13`. The dependencies should be up to date. Please try it in an empty environment and do not hesitate to let me know if you still have similar issues:

```
absl-py==1.1.0
appdirs==1.4.4
attrs==21.4.0
audioread==2.1.9
cachetools==5.2.0
certifi==2022.5.18.1
cffi==1.15.0
charset-normalizer==2.0.12
cycler==0.11.0
decorator==5.1.1
ear==2.1.0
fonttools==4.33.3
google-auth==2.7.0
google-auth-oauthlib==0.4.6
grpcio==1.46.3
idna==3.3
imageio==2.19.3
importlib-metadata==4.11.4
joblib==1.1.0
kiwisolver==1.4.2
librosa==0.9.1
llvmlite==0.38.1
lxml==4.9.0
Markdown==3.3.7
matplotlib==3.5.2
multipledispatch==0.6.0
networkx==2.8.3
numba==0.55.2
numpy==1.22.4
oauthlib==3.2.0
packaging==21.3
pandas==1.4.2
pesq==0.0.4
Pillow==9.1.1
pooch==1.6.0
prettytable==3.3.0
protobuf==3.19.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyparsing==3.0.9
pystoi==0.3.3
python-dateutil==2.8.2
pytz==2022.1
pyvad==0.1.3
PyWavelets==1.3.0
requests==2.28.0
requests-oauthlib==1.3.1
resampy==0.2.2
rsa==4.8
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
scikit-image==0.19.2
scikit-learn==1.1.1
scipy==1.8.1
six==1.16.0
SoundFile==0.10.3.post1
speechpy==2.4
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
tifffile==2022.5.4
torch==1.11.0
torchaudio==0.11.0
torchvision==0.12.0
tqdm==4.64.0
typing_extensions==4.2.0
urllib3==1.26.9
wavinfo==1.6.3
wcwidth==0.2.5
webrtcvad==2.0.10
Werkzeug==2.1.2
zipp==3.8.0
```

**Comment by zuowanbushiwo** [comment]
@eagomez2 
 Thanks，Works perfectly with the latest files,  and  I test python3.6.9 also can. it's a really great open source project.
